name: ci

on:
  pull_request:
    branches:
      - main
      - dev
  push:
    branches:
      - main
      - dev

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
      - name: Install dependencies
        run: yarn install
      - name: Format package.json
        run: yarn biome check package.json --write
      - name: Check
        run: yarn check-all